#!/bin/sh
set -e
usage() {
    echo "Usage: $0 <repo URL>"
    echo "Clones a source code repository (git only for now) temporarily."
}

[ -z "$1" ] && usage && exit 2
[ "$1" = "-h" ] && usage && exit 0

set -u
GITURL="$1"
TDIR="$(mktemp -d)"
cd "${TDIR}"
git clone --depth 2 "${GITURL}"
echo "Starting a new shell. Exiting will remove the directory."
cd *
$SHELL
rm -rf "${TDIR}"
